<?php

return [
    /**
     * The Template Attributes
     */
    'attributes' => [
        'size',
        'character_race',
	'character_class',
	'character_level',
	'experience',
        'alignment',
        'armor_class',
	'proficiency',
	'initiative',
        'hit_points',
	'hit_dice',
        'speed',
        'str',
        'dex',
        'con',
        'int',
        'wis',
        'cha',
        'saving_throws',
        'skills',
        'damage_resistances',
        'damage_immunities',
        'condition_immunities',
        'senses',
        'languages',
	'proficiencies_armor',
	'proficiencies_weapons',
	'proficiences_other',
	'spellcasting_class',
	'spellcasting_attribute',
	'spellcasting_attack',
	'spellcasting_save',
	'spellcasting_to_prep',
	'spellcasting_cantrips',
	'spellcasting_prepared' => ['type' => 'text'],
	'spellcasting_known' => ['type' => 'text'], 
        'spells_at_will',
        'spells_once',
        'spells_three',
        'feature_1' => ['type' => 'text'],
        'feature_2' => ['type' => 'text'],
        'feature_3' => ['type' => 'text'],
        'multiattack',
        'attack_1' => ['type' => 'text'],
        'attack_2' => ['type' => 'text'],
        'attack_3' => ['type' => 'text'],
        'ability_1' => ['type' => 'text'],
        'ability_2' => ['type' => 'text'],
        'ability_3' => ['type' => 'text'],
        'reaction_1' => ['type' => 'text'],
        'reaction_2' => ['type' => 'text'],
        'reaction_3' => ['type' => 'text'],
        'innate_spellcasting' => ['type' => 'text'],
        'magic_resistance' => ['type' => 'text'],
        'magic_weapons' => ['type' => 'text'],
        'regeneration' => ['type' => 'text'],
        'legendary_resistance' => ['type' => 'text'],
        'legendary_action_1' => ['type' => 'text'],
        'legendary_action_2' => ['type' => 'text'],
        'legendary_action_3' => ['type' => 'text'],
        'legendary_resistance_count',
        'legendary_actions' => ['type' => 'text'],
    ]
];
